/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as ApiOpenapiDotjsonRouteImport } from './routes/api/openapi[.]json'
import { Route as ApiV1AlbumsAppleIdRouteImport } from './routes/api/v1/albums/$appleId'
import { Route as ApiV1ArtistsAppleIdRouteImport } from './routes/api/v1/artists/$appleId'
import { Route as ApiV1AssetsBatchRouteImport } from './routes/api/v1/assets/batch'
import { Route as ApiV1CatalogBatchRouteImport } from './routes/api/v1/catalog/batch'
import { Route as ApiV1CatalogSearchRouteImport } from './routes/api/v1/catalog/search'
import { Route as ApiV1PlaylistsAppleIdRouteImport } from './routes/api/v1/playlists/$appleId'
import { Route as ApiV1RecordLabelsAppleIdRouteImport } from './routes/api/v1/record-labels/$appleId'
import { Route as ApiV1TracksAppleIdRouteImport } from './routes/api/v1/tracks/$appleId'
import { Route as ApiV1TracksBatchRouteImport } from './routes/api/v1/tracks/batch'
import { Route as ApiV1CatalogSearchHintsRouteImport } from './routes/api/v1/catalog/search/hints'
import { Route as ApiV1CatalogSearchSuggestionsRouteImport } from './routes/api/v1/catalog/search/suggestions'
import { Route as ApiV1AlbumsAppleIdCollectionsCollectionRouteImport } from './routes/api/v1/albums/$appleId/collections/$collection'
import { Route as ApiV1ArtistsAppleIdCollectionsCollectionRouteImport } from './routes/api/v1/artists/$appleId/collections/$collection'
import { Route as ApiV1PlaylistsAppleIdCollectionsCollectionRouteImport } from './routes/api/v1/playlists/$appleId/collections/$collection'
import { Route as ApiV1RecordLabelsAppleIdCollectionsCollectionRouteImport } from './routes/api/v1/record-labels/$appleId/collections/$collection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRoute = ApiOpenapiDotjsonRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AlbumsAppleIdRoute = ApiV1AlbumsAppleIdRouteImport.update({
  id: '/api/v1/albums/$appleId',
  path: '/api/v1/albums/$appleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ArtistsAppleIdRoute = ApiV1ArtistsAppleIdRouteImport.update({
  id: '/api/v1/artists/$appleId',
  path: '/api/v1/artists/$appleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AssetsBatchRoute = ApiV1AssetsBatchRouteImport.update({
  id: '/api/v1/assets/batch',
  path: '/api/v1/assets/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CatalogBatchRoute = ApiV1CatalogBatchRouteImport.update({
  id: '/api/v1/catalog/batch',
  path: '/api/v1/catalog/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CatalogSearchRoute = ApiV1CatalogSearchRouteImport.update({
  id: '/api/v1/catalog/search',
  path: '/api/v1/catalog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PlaylistsAppleIdRoute = ApiV1PlaylistsAppleIdRouteImport.update({
  id: '/api/v1/playlists/$appleId',
  path: '/api/v1/playlists/$appleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RecordLabelsAppleIdRoute =
  ApiV1RecordLabelsAppleIdRouteImport.update({
    id: '/api/v1/record-labels/$appleId',
    path: '/api/v1/record-labels/$appleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1TracksAppleIdRoute = ApiV1TracksAppleIdRouteImport.update({
  id: '/api/v1/tracks/$appleId',
  path: '/api/v1/tracks/$appleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TracksBatchRoute = ApiV1TracksBatchRouteImport.update({
  id: '/api/v1/tracks/batch',
  path: '/api/v1/tracks/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CatalogSearchHintsRoute = ApiV1CatalogSearchHintsRouteImport.update({
  id: '/hints',
  path: '/hints',
  getParentRoute: () => ApiV1CatalogSearchRoute,
} as any)
const ApiV1CatalogSearchSuggestionsRoute =
  ApiV1CatalogSearchSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => ApiV1CatalogSearchRoute,
  } as any)
const ApiV1AlbumsAppleIdCollectionsCollectionRoute =
  ApiV1AlbumsAppleIdCollectionsCollectionRouteImport.update({
    id: '/collections/$collection',
    path: '/collections/$collection',
    getParentRoute: () => ApiV1AlbumsAppleIdRoute,
  } as any)
const ApiV1ArtistsAppleIdCollectionsCollectionRoute =
  ApiV1ArtistsAppleIdCollectionsCollectionRouteImport.update({
    id: '/collections/$collection',
    path: '/collections/$collection',
    getParentRoute: () => ApiV1ArtistsAppleIdRoute,
  } as any)
const ApiV1PlaylistsAppleIdCollectionsCollectionRoute =
  ApiV1PlaylistsAppleIdCollectionsCollectionRouteImport.update({
    id: '/collections/$collection',
    path: '/collections/$collection',
    getParentRoute: () => ApiV1PlaylistsAppleIdRoute,
  } as any)
const ApiV1RecordLabelsAppleIdCollectionsCollectionRoute =
  ApiV1RecordLabelsAppleIdCollectionsCollectionRouteImport.update({
    id: '/collections/$collection',
    path: '/collections/$collection',
    getParentRoute: () => ApiV1RecordLabelsAppleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/v1/albums/$appleId': typeof ApiV1AlbumsAppleIdRouteWithChildren
  '/api/v1/artists/$appleId': typeof ApiV1ArtistsAppleIdRouteWithChildren
  '/api/v1/assets/batch': typeof ApiV1AssetsBatchRoute
  '/api/v1/catalog/batch': typeof ApiV1CatalogBatchRoute
  '/api/v1/catalog/search': typeof ApiV1CatalogSearchRouteWithChildren
  '/api/v1/playlists/$appleId': typeof ApiV1PlaylistsAppleIdRouteWithChildren
  '/api/v1/record-labels/$appleId': typeof ApiV1RecordLabelsAppleIdRouteWithChildren
  '/api/v1/tracks/$appleId': typeof ApiV1TracksAppleIdRoute
  '/api/v1/tracks/batch': typeof ApiV1TracksBatchRoute
  '/api/v1/catalog/search/hints': typeof ApiV1CatalogSearchHintsRoute
  '/api/v1/catalog/search/suggestions': typeof ApiV1CatalogSearchSuggestionsRoute
  '/api/v1/albums/$appleId/collections/$collection': typeof ApiV1AlbumsAppleIdCollectionsCollectionRoute
  '/api/v1/artists/$appleId/collections/$collection': typeof ApiV1ArtistsAppleIdCollectionsCollectionRoute
  '/api/v1/playlists/$appleId/collections/$collection': typeof ApiV1PlaylistsAppleIdCollectionsCollectionRoute
  '/api/v1/record-labels/$appleId/collections/$collection': typeof ApiV1RecordLabelsAppleIdCollectionsCollectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/v1/albums/$appleId': typeof ApiV1AlbumsAppleIdRouteWithChildren
  '/api/v1/artists/$appleId': typeof ApiV1ArtistsAppleIdRouteWithChildren
  '/api/v1/assets/batch': typeof ApiV1AssetsBatchRoute
  '/api/v1/catalog/batch': typeof ApiV1CatalogBatchRoute
  '/api/v1/catalog/search': typeof ApiV1CatalogSearchRouteWithChildren
  '/api/v1/playlists/$appleId': typeof ApiV1PlaylistsAppleIdRouteWithChildren
  '/api/v1/record-labels/$appleId': typeof ApiV1RecordLabelsAppleIdRouteWithChildren
  '/api/v1/tracks/$appleId': typeof ApiV1TracksAppleIdRoute
  '/api/v1/tracks/batch': typeof ApiV1TracksBatchRoute
  '/api/v1/catalog/search/hints': typeof ApiV1CatalogSearchHintsRoute
  '/api/v1/catalog/search/suggestions': typeof ApiV1CatalogSearchSuggestionsRoute
  '/api/v1/albums/$appleId/collections/$collection': typeof ApiV1AlbumsAppleIdCollectionsCollectionRoute
  '/api/v1/artists/$appleId/collections/$collection': typeof ApiV1ArtistsAppleIdCollectionsCollectionRoute
  '/api/v1/playlists/$appleId/collections/$collection': typeof ApiV1PlaylistsAppleIdCollectionsCollectionRoute
  '/api/v1/record-labels/$appleId/collections/$collection': typeof ApiV1RecordLabelsAppleIdCollectionsCollectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRoute
  '/api/v1/albums/$appleId': typeof ApiV1AlbumsAppleIdRouteWithChildren
  '/api/v1/artists/$appleId': typeof ApiV1ArtistsAppleIdRouteWithChildren
  '/api/v1/assets/batch': typeof ApiV1AssetsBatchRoute
  '/api/v1/catalog/batch': typeof ApiV1CatalogBatchRoute
  '/api/v1/catalog/search': typeof ApiV1CatalogSearchRouteWithChildren
  '/api/v1/playlists/$appleId': typeof ApiV1PlaylistsAppleIdRouteWithChildren
  '/api/v1/record-labels/$appleId': typeof ApiV1RecordLabelsAppleIdRouteWithChildren
  '/api/v1/tracks/$appleId': typeof ApiV1TracksAppleIdRoute
  '/api/v1/tracks/batch': typeof ApiV1TracksBatchRoute
  '/api/v1/catalog/search/hints': typeof ApiV1CatalogSearchHintsRoute
  '/api/v1/catalog/search/suggestions': typeof ApiV1CatalogSearchSuggestionsRoute
  '/api/v1/albums/$appleId/collections/$collection': typeof ApiV1AlbumsAppleIdCollectionsCollectionRoute
  '/api/v1/artists/$appleId/collections/$collection': typeof ApiV1ArtistsAppleIdCollectionsCollectionRoute
  '/api/v1/playlists/$appleId/collections/$collection': typeof ApiV1PlaylistsAppleIdCollectionsCollectionRoute
  '/api/v1/record-labels/$appleId/collections/$collection': typeof ApiV1RecordLabelsAppleIdCollectionsCollectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/v1/albums/$appleId'
    | '/api/v1/artists/$appleId'
    | '/api/v1/assets/batch'
    | '/api/v1/catalog/batch'
    | '/api/v1/catalog/search'
    | '/api/v1/playlists/$appleId'
    | '/api/v1/record-labels/$appleId'
    | '/api/v1/tracks/$appleId'
    | '/api/v1/tracks/batch'
    | '/api/v1/catalog/search/hints'
    | '/api/v1/catalog/search/suggestions'
    | '/api/v1/albums/$appleId/collections/$collection'
    | '/api/v1/artists/$appleId/collections/$collection'
    | '/api/v1/playlists/$appleId/collections/$collection'
    | '/api/v1/record-labels/$appleId/collections/$collection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/v1/albums/$appleId'
    | '/api/v1/artists/$appleId'
    | '/api/v1/assets/batch'
    | '/api/v1/catalog/batch'
    | '/api/v1/catalog/search'
    | '/api/v1/playlists/$appleId'
    | '/api/v1/record-labels/$appleId'
    | '/api/v1/tracks/$appleId'
    | '/api/v1/tracks/batch'
    | '/api/v1/catalog/search/hints'
    | '/api/v1/catalog/search/suggestions'
    | '/api/v1/albums/$appleId/collections/$collection'
    | '/api/v1/artists/$appleId/collections/$collection'
    | '/api/v1/playlists/$appleId/collections/$collection'
    | '/api/v1/record-labels/$appleId/collections/$collection'
  id:
    | '__root__'
    | '/'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/v1/albums/$appleId'
    | '/api/v1/artists/$appleId'
    | '/api/v1/assets/batch'
    | '/api/v1/catalog/batch'
    | '/api/v1/catalog/search'
    | '/api/v1/playlists/$appleId'
    | '/api/v1/record-labels/$appleId'
    | '/api/v1/tracks/$appleId'
    | '/api/v1/tracks/batch'
    | '/api/v1/catalog/search/hints'
    | '/api/v1/catalog/search/suggestions'
    | '/api/v1/albums/$appleId/collections/$collection'
    | '/api/v1/artists/$appleId/collections/$collection'
    | '/api/v1/playlists/$appleId/collections/$collection'
    | '/api/v1/record-labels/$appleId/collections/$collection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiOpenapiDotjsonRoute: typeof ApiOpenapiDotjsonRoute
  ApiV1AlbumsAppleIdRoute: typeof ApiV1AlbumsAppleIdRouteWithChildren
  ApiV1ArtistsAppleIdRoute: typeof ApiV1ArtistsAppleIdRouteWithChildren
  ApiV1AssetsBatchRoute: typeof ApiV1AssetsBatchRoute
  ApiV1CatalogBatchRoute: typeof ApiV1CatalogBatchRoute
  ApiV1CatalogSearchRoute: typeof ApiV1CatalogSearchRouteWithChildren
  ApiV1PlaylistsAppleIdRoute: typeof ApiV1PlaylistsAppleIdRouteWithChildren
  ApiV1RecordLabelsAppleIdRoute: typeof ApiV1RecordLabelsAppleIdRouteWithChildren
  ApiV1TracksAppleIdRoute: typeof ApiV1TracksAppleIdRoute
  ApiV1TracksBatchRoute: typeof ApiV1TracksBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/albums/$appleId': {
      id: '/api/v1/albums/$appleId'
      path: '/api/v1/albums/$appleId'
      fullPath: '/api/v1/albums/$appleId'
      preLoaderRoute: typeof ApiV1AlbumsAppleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/artists/$appleId': {
      id: '/api/v1/artists/$appleId'
      path: '/api/v1/artists/$appleId'
      fullPath: '/api/v1/artists/$appleId'
      preLoaderRoute: typeof ApiV1ArtistsAppleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/assets/batch': {
      id: '/api/v1/assets/batch'
      path: '/api/v1/assets/batch'
      fullPath: '/api/v1/assets/batch'
      preLoaderRoute: typeof ApiV1AssetsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/catalog/batch': {
      id: '/api/v1/catalog/batch'
      path: '/api/v1/catalog/batch'
      fullPath: '/api/v1/catalog/batch'
      preLoaderRoute: typeof ApiV1CatalogBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/catalog/search': {
      id: '/api/v1/catalog/search'
      path: '/api/v1/catalog/search'
      fullPath: '/api/v1/catalog/search'
      preLoaderRoute: typeof ApiV1CatalogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/playlists/$appleId': {
      id: '/api/v1/playlists/$appleId'
      path: '/api/v1/playlists/$appleId'
      fullPath: '/api/v1/playlists/$appleId'
      preLoaderRoute: typeof ApiV1PlaylistsAppleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/record-labels/$appleId': {
      id: '/api/v1/record-labels/$appleId'
      path: '/api/v1/record-labels/$appleId'
      fullPath: '/api/v1/record-labels/$appleId'
      preLoaderRoute: typeof ApiV1RecordLabelsAppleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tracks/$appleId': {
      id: '/api/v1/tracks/$appleId'
      path: '/api/v1/tracks/$appleId'
      fullPath: '/api/v1/tracks/$appleId'
      preLoaderRoute: typeof ApiV1TracksAppleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tracks/batch': {
      id: '/api/v1/tracks/batch'
      path: '/api/v1/tracks/batch'
      fullPath: '/api/v1/tracks/batch'
      preLoaderRoute: typeof ApiV1TracksBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/catalog/search/hints': {
      id: '/api/v1/catalog/search/hints'
      path: '/hints'
      fullPath: '/api/v1/catalog/search/hints'
      preLoaderRoute: typeof ApiV1CatalogSearchHintsRouteImport
      parentRoute: typeof ApiV1CatalogSearchRoute
    }
    '/api/v1/catalog/search/suggestions': {
      id: '/api/v1/catalog/search/suggestions'
      path: '/suggestions'
      fullPath: '/api/v1/catalog/search/suggestions'
      preLoaderRoute: typeof ApiV1CatalogSearchSuggestionsRouteImport
      parentRoute: typeof ApiV1CatalogSearchRoute
    }
    '/api/v1/albums/$appleId/collections/$collection': {
      id: '/api/v1/albums/$appleId/collections/$collection'
      path: '/collections/$collection'
      fullPath: '/api/v1/albums/$appleId/collections/$collection'
      preLoaderRoute: typeof ApiV1AlbumsAppleIdCollectionsCollectionRouteImport
      parentRoute: typeof ApiV1AlbumsAppleIdRoute
    }
    '/api/v1/artists/$appleId/collections/$collection': {
      id: '/api/v1/artists/$appleId/collections/$collection'
      path: '/collections/$collection'
      fullPath: '/api/v1/artists/$appleId/collections/$collection'
      preLoaderRoute: typeof ApiV1ArtistsAppleIdCollectionsCollectionRouteImport
      parentRoute: typeof ApiV1ArtistsAppleIdRoute
    }
    '/api/v1/playlists/$appleId/collections/$collection': {
      id: '/api/v1/playlists/$appleId/collections/$collection'
      path: '/collections/$collection'
      fullPath: '/api/v1/playlists/$appleId/collections/$collection'
      preLoaderRoute: typeof ApiV1PlaylistsAppleIdCollectionsCollectionRouteImport
      parentRoute: typeof ApiV1PlaylistsAppleIdRoute
    }
    '/api/v1/record-labels/$appleId/collections/$collection': {
      id: '/api/v1/record-labels/$appleId/collections/$collection'
      path: '/collections/$collection'
      fullPath: '/api/v1/record-labels/$appleId/collections/$collection'
      preLoaderRoute: typeof ApiV1RecordLabelsAppleIdCollectionsCollectionRouteImport
      parentRoute: typeof ApiV1RecordLabelsAppleIdRoute
    }
  }
}

interface ApiV1AlbumsAppleIdRouteChildren {
  ApiV1AlbumsAppleIdCollectionsCollectionRoute: typeof ApiV1AlbumsAppleIdCollectionsCollectionRoute
}

const ApiV1AlbumsAppleIdRouteChildren: ApiV1AlbumsAppleIdRouteChildren = {
  ApiV1AlbumsAppleIdCollectionsCollectionRoute:
    ApiV1AlbumsAppleIdCollectionsCollectionRoute,
}

const ApiV1AlbumsAppleIdRouteWithChildren =
  ApiV1AlbumsAppleIdRoute._addFileChildren(ApiV1AlbumsAppleIdRouteChildren)

interface ApiV1ArtistsAppleIdRouteChildren {
  ApiV1ArtistsAppleIdCollectionsCollectionRoute: typeof ApiV1ArtistsAppleIdCollectionsCollectionRoute
}

const ApiV1ArtistsAppleIdRouteChildren: ApiV1ArtistsAppleIdRouteChildren = {
  ApiV1ArtistsAppleIdCollectionsCollectionRoute:
    ApiV1ArtistsAppleIdCollectionsCollectionRoute,
}

const ApiV1ArtistsAppleIdRouteWithChildren =
  ApiV1ArtistsAppleIdRoute._addFileChildren(ApiV1ArtistsAppleIdRouteChildren)

interface ApiV1CatalogSearchRouteChildren {
  ApiV1CatalogSearchHintsRoute: typeof ApiV1CatalogSearchHintsRoute
  ApiV1CatalogSearchSuggestionsRoute: typeof ApiV1CatalogSearchSuggestionsRoute
}

const ApiV1CatalogSearchRouteChildren: ApiV1CatalogSearchRouteChildren = {
  ApiV1CatalogSearchHintsRoute: ApiV1CatalogSearchHintsRoute,
  ApiV1CatalogSearchSuggestionsRoute: ApiV1CatalogSearchSuggestionsRoute,
}

const ApiV1CatalogSearchRouteWithChildren =
  ApiV1CatalogSearchRoute._addFileChildren(ApiV1CatalogSearchRouteChildren)

interface ApiV1PlaylistsAppleIdRouteChildren {
  ApiV1PlaylistsAppleIdCollectionsCollectionRoute: typeof ApiV1PlaylistsAppleIdCollectionsCollectionRoute
}

const ApiV1PlaylistsAppleIdRouteChildren: ApiV1PlaylistsAppleIdRouteChildren = {
  ApiV1PlaylistsAppleIdCollectionsCollectionRoute:
    ApiV1PlaylistsAppleIdCollectionsCollectionRoute,
}

const ApiV1PlaylistsAppleIdRouteWithChildren =
  ApiV1PlaylistsAppleIdRoute._addFileChildren(
    ApiV1PlaylistsAppleIdRouteChildren,
  )

interface ApiV1RecordLabelsAppleIdRouteChildren {
  ApiV1RecordLabelsAppleIdCollectionsCollectionRoute: typeof ApiV1RecordLabelsAppleIdCollectionsCollectionRoute
}

const ApiV1RecordLabelsAppleIdRouteChildren: ApiV1RecordLabelsAppleIdRouteChildren =
  {
    ApiV1RecordLabelsAppleIdCollectionsCollectionRoute:
      ApiV1RecordLabelsAppleIdCollectionsCollectionRoute,
  }

const ApiV1RecordLabelsAppleIdRouteWithChildren =
  ApiV1RecordLabelsAppleIdRoute._addFileChildren(
    ApiV1RecordLabelsAppleIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiOpenapiDotjsonRoute: ApiOpenapiDotjsonRoute,
  ApiV1AlbumsAppleIdRoute: ApiV1AlbumsAppleIdRouteWithChildren,
  ApiV1ArtistsAppleIdRoute: ApiV1ArtistsAppleIdRouteWithChildren,
  ApiV1AssetsBatchRoute: ApiV1AssetsBatchRoute,
  ApiV1CatalogBatchRoute: ApiV1CatalogBatchRoute,
  ApiV1CatalogSearchRoute: ApiV1CatalogSearchRouteWithChildren,
  ApiV1PlaylistsAppleIdRoute: ApiV1PlaylistsAppleIdRouteWithChildren,
  ApiV1RecordLabelsAppleIdRoute: ApiV1RecordLabelsAppleIdRouteWithChildren,
  ApiV1TracksAppleIdRoute: ApiV1TracksAppleIdRoute,
  ApiV1TracksBatchRoute: ApiV1TracksBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
